In [2]:
import pandas as pd
import numpy as np

In [13]:
Amazonsales= pd.read_csv('Amazon Sale Report.csv')
Amazonsales.head()

C:\Users\saheed samad\AppData\Local\Temp\ipykernel_1284\1059855247.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  Amazonsales= pd.read_csv('Amazon Sale Report.csv')

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [5]:
# Drop the last column
Amazonsales.drop(Amazonsales.columns[-1], axis=1, inplace=True)

# Verify the change
print("Updated Columns:")
print(Amazonsales.columns)

Updated Columns:
Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='object')

In [6]:
# Check the data types of each column
print("Data Types of Each Column:")
print(Amazonsales.dtypes)

Data Types of Each Column:
index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
dtype: object

In [7]:
# Correct Data Types

# Convert 'Date' column to datetime
Amazonsales['Date'] = pd.to_datetime(Amazonsales['Date'], errors='coerce')

# Convert 'ship-postal-code' to string (object)
Amazonsales['ship-postal-code'] = Amazonsales['ship-postal-code'].astype(str)

# Verify the corrected data types
print("\nData Types After Correction:")
print(Amazonsales.dtypes)

Data Types After Correction:
index                          int64
Order ID                      object
Date                  datetime64[ns]
Status                        object
Fulfilment                    object
Sales Channel                 object
ship-service-level            object
Style                         object
SKU                           object
Category                      object
Size                          object
ASIN                          object
Courier Status                object
Qty                            int64
currency                      object
Amount                       float64
ship-city                     object
ship-state                    object
ship-postal-code              object
ship-country                  object
promotion-ids                 object
B2B                             bool
fulfilled-by                  object
dtype: object

In [8]:
# Check for duplicate rows
duplicate_count = Amazonsales.duplicated().sum()

# Print the number of duplicate rows
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [9]:
# Check for null values in each column
null_values = Amazonsales.isnull().sum()

# Print the null values for each column
print("Null Values in Each Column:")
print(null_values)

Null Values in Each Column:
index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code          0
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
dtype: int64

In [11]:


# 1. Fill 'Courier Status' with 'Not Available'
Amazonsales['Courier Status'].fillna('Not Available', inplace=True)

# 2. Fill 'currency' with the mode (most common value)
if 'currency' in Amazonsales.columns:
    currency_mode = Amazonsales['currency'].mode()[0]
    Amazonsales['currency'].fillna(currency_mode, inplace=True)

# 3. Replace nulls in 'Amount' with 0
Amazonsales['Amount'].fillna(0, inplace=True)

# 4. Fill 'ship-city', 'ship-state', 'ship-country' with 'Unknown'
Amazonsales['ship-city'].fillna('Unknown', inplace=True)
Amazonsales['ship-state'].fillna('Unknown', inplace=True)
Amazonsales['ship-country'].fillna('Unknown', inplace=True)

# 5. Replace nulls in 'promotion-ids' with 'No Promotion'
Amazonsales['promotion-ids'].fillna('No Promotion', inplace=True)

# 6. Fill 'fulfilled-by' with 'Not Specified'
Amazonsales['fulfilled-by'].fillna('Not Specified', inplace=True)

# Verify changes
print("Null Values After Cleaning:")
print(Amazonsales.isnull().sum())

Null Values After Cleaning:
index                 0
Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
promotion-ids         0
B2B                   0
fulfilled-by          0
dtype: int64

In [12]:
# Save the cleaned dataset to a new CSV file
cleaned_file_path = 'cleaned_amazon_sale_report.csv'  # Replace with your desired file name
Amazonsales.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved as '{cleaned_file_path}'")

Cleaned dataset saved as 'cleaned_amazon_sale_report.csv'